### ISSUE TITLE
Host internal staff user research

### ISSUE THREAD

**Issue by migurski** [mapzen/mapzen.js#103]
Interview John, Alyssa, Randy, and other Mapzen targets from phase one to learn about their responses to initial Web Map release and needs for subsequent releases.

**Comment by migurski** [comment]
Removing this from Round Two, so we can put it to bed.

**Comment by hanbyul-here** [comment]
Now we are main consumer of mapzen.js and in the phase of talking about outside of Mapzen research. So closing this issue.
