### ISSUE TITLE
Figure out standards for attribution

### ISSUE THREAD

**Issue by souperneon** [mapzen/mapzen.js#119]
Our attribution is a little all over the place. Let's define certain standards for our own demos with web map
1. Just map with scarab
2. Tangram map with search 
3. Tangram map with search and routing
More examples?

**Comment by hanbyul-here** [comment]
This probably needs to take priority, who should we talk @migurski ?

**Comment by souperneon** [comment]
@rmglennon did you have any thoughts on this?

**Comment by hanbyul-here** [comment]
We decided to follow  https://mapzen.com/rights/ , we can change it whenever we feel need.

**Comment by rmglennon** [comment]
Dave R, @migurski, and I were doing some work in this area, and we should pick up again. In terms of what exactly goes on the map, @randymeech had suggested that Mapzen be in the map attribution if our web services are being used. 

For #162, I'd remove the "Powered by" part of the attribution on a map, though (even though it is listed on the /rights page). Leaflet did this a few years ago (search for "powered by leaflet" for some GitHub issues and Google threads) to simplify.

**Comment by mjcunningham** [comment]
@rmglennon we can make that the out of the box implementation for mobile too.

**Comment by hanbyul-here** [comment]
closed via 862b7cab9ce0c8250ccdb057426038ceb50b60ee
