### ISSUE TITLE
Figure out where GA events go

### ISSUE THREAD

**Issue by migurski** [mapzen/mapzen.js#149]
There are events from the Scarab, right? Where do they go?

**Comment by hanbyul-here** [comment]
@mjcunningham  do you know where the events of Mapzen Scarab go?

**Comment by mjcunningham** [comment]
They fall under the "demo" event. 

@louh worked on this so he might remember what the labels are better than I can. 

What were the "fallback" and "active" label for again? The "click" action and subsequent labels are pretty self explanatory.

**Comment by migurski** [comment]
What would be the outcome of changing the event name from "demo" to something like "mapzen.js scarab" ?

**Comment by mjcunningham** [comment]
I think that GA doesn't rename the old events, which isn't a big deal except for historical analysis of that feature.

**Comment by migurski** [comment]
Do you think that anyone’s looking at that now?

**Comment by mjcunningham** [comment]
I do not.

**Comment by migurski** [comment]
Figured out that [they go to "demo"](https://analytics.google.com/analytics/web/#report/content-event-events/a47035811w78197217p80848516/%3F_u.date00%3D20160406%26_u.date01%3D20160706%26explorer-segmentExplorer.segmentId%3Danalytics.eventCategory%26_r.drilldown%3Danalytics.eventCategory%3Ademo%26explorer-table.secSegmentId%3Danalytics.eventLabel%26explorer-table.plotKeys%3D%5B%5D%26explorer-table-tableMode.selected%3Dpie/). Closing this in favor of #183.
