### ISSUE TITLE
Attribution confuses Geocoding & Tangram

### ISSUE THREAD

**Issue by nvkelso** [mapzen/mapzen.js#162]
Seems like Tangram is part of geocoding? Why two Mapzen mentions?

`Leaflet | Geocoding by Mapzen, Tangram | © OSM contributors | Mapzen`

to

`Geocoding by Mapzen | Tangram | Leaflet | © OSM contributors`

**Comment by hanbyul-here** [comment]
Geocoder and Tangram component is not communicating each other about attribution, so two Mapzen mentions came from each component. I left the attribution part out in a hope https://github.com/mapzen/mapzen.js/issues/119 is going to be resolved soon.

**Comment by hanbyul-here** [comment]
closed via 862b7cab9ce0c8250ccdb057426038ceb50b60ee
