### ISSUE TITLE
Should HouseStyle be MapStyle?

### ISSUE THREAD

**Issue by nvkelso** [mapzen/mapzen.js#163]
For instance, `L.Mapzen.HouseStyles.BubbleWrap`. **HouseStyle** here feels more like insider baseball / a description and something like **MapStyle** more generically a title?

**Comment by migurski** [comment]
I don’t have a strong preference here. “House” seems like a nice way to talk about them being ours, while "map" is as you say more neutral.

**Comment by rmglennon** [comment]
My first thought was that House Styles could be taken literally, as in drawing a residential building, especially when translated. It is also kind of vague about what it performs.

Other options:
- basemap styles
- map styles
- Mapzen styles (although weird to repeat Mapzen with the namespace?)
- basemaps
- stylesheets
- styles

Quick check through various Leaflet references and documentation:
L.esri.basemapLayer("Gray") - Esri = basemap
mapbox://styles/mapbox/basic-v9 Mapbox = styles
CartoDB = basemap

Perhaps some variety of basemap, if these are all planned to be basemaps (which is what we've called them in the [blog](https://mapzen.com/blog/introducing-refill-cinnabar-and-zinc-styles-for-tangram/))?

**Comment by migurski** [comment]
If we use the term "basemap", does that exclude things like Tron? Should it?

**Comment by migurski** [comment]
Decision from @nvkelso and @rmglennon: `L.Mapzen.BasemapStyle.Blah`.

**Comment by migurski** [comment]
(and backwards-compatible `L.Mapzen.HouseStyles` until 1.0)

**Comment by nvkelso** [comment]
(Something else I've seen is "default map styles", which might be good for SEO somewhere on the Maps product page.)
