### ISSUE TITLE
BubbleWrap house style is using an older version

### ISSUE THREAD

**Issue by nvkelso** [mapzen/mapzen.js#164]
There is a blue line (country boundary in the water) appearing in the demos. Looking at your code it looks like you're doing everything correctly which means I probably missed a step during cartography release management. Filing this here since we should fix this for the library, but it's probably an upstream / configuration changed fix.

**Comment by hanbyul-here** [comment]
I assume this can be closed with #237  ? @nvkelso ?

**Comment by nvkelso** [comment]
Yes, when I load https://mapzen.com/products/maps/ I no longer see the blue line and looking at network traffic on that page I see it's sourcing correctly now from:

- https://mapzen.com/carto/bubble-wrap-style/4/bubble-wrap.yaml
