### ISSUE TITLE
Improving API reference

### ISSUE THREAD

**Issue by kkowalsky** [mapzen/mapzen.js#170]
I'm having trouble migrating some code to Mapzen.js because of the lack of detail in the API reference (i.e. with L.mapzen.map you have to include center and zoom descriptions). I'll keep track of what to include in the reference. Anyone else that has problems with the reference should also post it here.

**Comment by kkowalsky** [comment]
https://github.com/mapzen/mapzen.js/issues/171

**Comment by hanbyul-here** [comment]
When we did test with @tigerlily-he, we found several points to improve.

1. When we asked Lilly to make a map with mapzen.js and gave a url for the repo, Lilly started building `mapzen.js` which is super cool, but we probably need to make it clear the url that user can grab `mapzen.js` from.

2. `Hash` term is confusing term for first time users, people don't consider `hash` is the component that saves the states of the map.

3. We put place holder for API key (`<your-api-key.`) , but users usually just copy whole code snippet and run it without looking back. It even shows the search component on the map, but throws an error when users start interacting. It will be good to have comment about api key, so people can look at it right away, know where to make one. 

4. @rmglennon suggested we need short explanation about what `mapzen.js` does. It goes directly to docs part now. Given the `README.md` is the only place user gets the information, it will be worth putting some words.

5. We still couldn't decide what to do about overwrapping documentation with other projects, but we agree that it is inconvenient to go to each page to find an option for each component.

**Comment by kkowalsky** [comment]
This is great feedback @hanbyul-here! Right now the generic API key thing is what we do throughout each product's documentation (don't want them using an API key that isn't specified to them!). We can link the fact that the user needs an API key better in the Mapzen.js documentation. 

Let me think about some organizational ways we can limit users having to go back forth for each component. Since Mapzen.js is meant to be used with each of our tools, it'll be a little tricky to implement documentation without having people have to switch between the pages but also being able to see how to mapzen.js on a particular product's docs.

**Comment by migurski** [comment]
With the recent move to keyless APIs, it seems like the copy-paste code actually skip keys.

**Comment by kkowalsky** [comment]
@rmglennon should we include documentation on both keyless and with key usage of tools? My concern is for people that overextend the generosity of keyless but don't know better.

**Comment by hanbyul-here** [comment]
@migurski I think it will still show 'wrong api key' warning because it is passing something (`<your-api-key>`) , not nothing

**Comment by migurski** [comment]
Can we change the samples so it passes nothing?

**Comment by kkowalsky** [comment]
created a new branch under kkowalsky-text-edit that is creating a docs folder to build a docs page for mapzen.js on the website. @rmglennon, take a look?
