### ISSUE TITLE
Geocoder doesn't collapse by default

### ISSUE THREAD

**Issue by kkowalsky** [mapzen/mapzen.js#171]
Despite being a default, L.Mapzen.geocoder won't collapse.

**Comment by kkowalsky** [comment]
<img width="1671" alt="screen shot 2016-06-27 at 2 15 59 pm" src="https://cloud.githubusercontent.com/assets/4246770/16396071/d4b13c48-3c71-11e6-9b41-eba4c4bd30fc.png">

`geocoder = L.Mapzen.geocoder('search-xxxxxx').addTo(map);`

**Comment by hanbyul-here** [comment]
- We thought current behavior (collapsing depending on the browser size) is desired default for demos. It is still worth having discussion we really want this for default or not.
```
      var geocoder = L.Mapzen.geocoder('search---------', {
        expanded: false,
        collapsible: false
      });
```
This will make geocoder collapse, This probably should go to documentation.

**Comment by kkowalsky** [comment]
yeah, that would be great.
