### ISSUE TITLE
Decide on release policy

### ISSUE THREAD

**Issue by migurski** [mapzen/mapzen.js#175]
Right now, `master` branch is live and changes are auto-published. By accepting PRs and not changing the content of `VERSION`, we’re breaking our Semver promise. New versions should at least get a patch version bump.

We can do one of three things:

1. Hold PRs for longer, and enforce the editing of `VERSION` when they are merged (and not after).
2. Introduce a new `release` (or similar) branch that actually pushes live, so we can accept PRs earlier.
3. Make publishing manual some other way.

In any of these case, I think we will want to prevent overwriting of previous releases, and potentially cause a failure when an overwrite is attempted.

**Comment by migurski** [comment]
PR #180 triggers a deployment error when new code is pushed to an old version.

**Comment by louh** [comment]
The Pelias team has been using [semantic-release](https://github.com/semantic-release/semantic-release) for the past month to automate semantic versioning and publishing. @orangejulius has some feelings about it, both good and bad. Worth having a chat with him about it!

**Comment by orangejulius** [comment]
Yup, the TLDR is it has some confusing features (continuously annoying), is somewhat hard to set up (initially annoying and then not a problem), still requires some human action to use (annoying since it's easy to forget), but when it works, it prevents a whole host of human errors around npm publishing and so is pretty nice! Happy to talk more about it.

**Comment by migurski** [comment]
Is it just for npm releases? We’re mostly releasing to S3.

**Comment by orangejulius** [comment]
Yeah, it's specifically for NPM.

**Comment by migurski** [comment]
@hanbyul-here and I made a plan this morning:

1. The VERSION and CHANGELOG files will be the source of truth for release information.
2. We will edit those files manually; semver requires conscious decisions to be made about the impact of changes, and those files are where we will make them.
3. Having a `release` branch is annoying; it amounts to the same thing as editing version numbers.
4. Everything will happen on `master`, and the diff check in `deploy.sh` will ensure that no previously-released version is ever re-used.
