### ISSUE TITLE
Template for 'component positioned in recommended spot' 

### ISSUE THREAD

**Issue by hanbyul-here** [mapzen/mapzen.js#176]
- We show our recommended positions for each components on erasermap.com/map , but it would be nice to have template for it.

**Comment by hanbyul-here** [comment]
I use `examples/index.html` to show all possible components in recommended spots. Can you mention about this in somewhere docs? @rmglennon @kkowalsky ?

**Comment by kkowalsky** [comment]
Yes, I can make a diagram that shows where every component is supposed to be positioned, is that you are thinking?

**Comment by hanbyul-here** [comment]
oh no, I meant that you can mention something like "You can find working example with all components in example folders" in docs.

**Comment by kkowalsky** [comment]
make sure to comment out the different components and that the source code assumes you've built the files but otherwise 👍
