### ISSUE TITLE
fallbacktile attribution

### ISSUE THREAD

**Issue by binx** [mapzen/mapzen.js#190]
Would it be possible to add a `fallbackAttribution` for `fallbackTile`?

**Comment by hanbyul-here** [comment]
`fallbackTile` is `L.tilelayer` http://leafletjs.com/reference.html#tilelayer , so you can send options as you send options to tilelayer. Syntax will be like `fallbackTile : L.tilelayer('tile-adress', {attribution: 'attribution-string'})`

**Comment by binx** [comment]
@hanbyul-here oh, cool! thank you for the explanation.
