### ISSUE TITLE
Expose tangram's getFeatureAt

### ISSUE THREAD

**Issue by binx** [mapzen/mapzen.js#195]
Could we please allow a `getFeatureAt` method so mapzen.js can have click events on map elements?

**Comment by hanbyul-here** [comment]
Yes we should ! This is definitely in our near future goal list.
While you waiting for it, you can still access to Tangram scene in this way ! : https://github.com/mapzen/website/blob/hanb/optimized-routing/resources/projects/turn-by-turn/optimized-routing/optimized-routing.js#L178

**Comment by migurski** [comment]
Guessing you meant this, right? https://github.com/mapzen/website/blob/6fd445ac3e91103d0fe011e01c31c16f75e9e411/resources/projects/turn-by-turn/optimized-routing/optimized-routing.js#L178

This need has come up for me, as well: https://github.com/mapzen/website/blob/2316603a91b9358cebea8ba21515c58c8394d627/products/maps.html#L58-L69

**Comment by hanbyul-here** [comment]
Oh right.. thank you @migurski
