### ISSUE TITLE
Peg Mapzen house styles to a version on the CDN

### ISSUE THREAD

**Issue by nvkelso** [mapzen/mapzen.js#210]
Right now these are all "latest", but that can create problems, especially as we reach towards v1 of vector tiles and v1 of Tangram and there are breaking changes that require a matched version.

Instead these should be pegged to a version number: https://github.com/mapzen/mapzen.js/blob/master/src/js/components/basemapStyles.js.

And in the future I'll send PRs here to rev Mapzen.js as whole to use new Tangram and House Style versions.

**Comment by hanbyul-here** [comment]
Do you have the version number for each style? Currently Mapzen.js is using Tangram 0.8

**Comment by migurski** [comment]
Yes, sounds good. Can you issue a PR here with the values you want?

**Comment by nvkelso** [comment]
I'll also update the Tangram version, looks like that's done here: https://github.com/mapzen/mapzen.js/blob/a6037879afad695cb1e993a5c828e997a80453d8/src/js/components/tangram.js#L12.

**Comment by nvkelso** [comment]
Although I'm unsure why it's also referring to a mix of v0.8 and v0.9 Tangram releases, here a couple lines below the last example: https://github.com/mapzen/mapzen.js/blob/a6037879afad695cb1e993a5c828e997a80453d8/src/js/components/tangram.js#L19.

**Comment by nvkelso** [comment]
I think this "test" should also be updated, right now it [points at a v0.4 Tangram](https://github.com/mapzen/mapzen.js/blob/c9cdc2cd9832df181f460ea14ea99fa5f2c070ce/test/index.html#L14) and we should probably use the same Tangram version everywhere in a mapzen.js release?

**Comment by migurski** [comment]
It should be 0.9 across the board. @hanbyul-here can you verify?

**Comment by hanbyul-here** [comment]
Yes, it should be 0.9, and only 0.9 is being used now. (`tangramURL` variable, which is referring 0.8 is not being used, `test.html` is also not being used) I will get rid of things pointing previous versions . Sorry for confusion.

**Comment by hanbyul-here** [comment]
closed through #237
