### ISSUE TITLE
Upgrade to Tangram 0.9.x

### ISSUE THREAD

**Issue by bcamper** [mapzen/mapzen.js#213]
Tangram 0.9 is here and [it's better](https://github.com/tangrams/tangram/releases/tag/v0.9.0)!

Let's upgrade to it at the next appropriate rev.

**Comment by migurski** [comment]
Yay! Any breaking API changes per our docs, or should this be a drop-in?

**Comment by bcamper** [comment]
Fully backward-compatible, we should be able to just drop it in.
