### ISSUE TITLE
Broken link on documentation page

### ISSUE THREAD

**Issue by tigerlily-he** [mapzen/mapzen.js#215]
In  https://mapzen.com/documentation/mapzen-js/search/#set-the-search-appearance-and-interaction-behavior, the link for "layer types" in the table for option = polygonIcon and option = pointIcon leads to this: 

https://mapzen.com/documentation/mapzen-js/(https://mapzen.com/documentation/search/search/#filter-by-data-type)

This is a broken link.

**Comment by rmglennon** [comment]
thanks @tigerlily-he!

I'll fix - there's an extra set of parentheses.
