### ISSUE TITLE
map.Locator request

### ISSUE THREAD

**Issue by thisisaaronland** [mapzen/mapzen.js#216]
It would be nice if there were an option for the `map.Locator` widget to trigger itself, without user intervention, when the page has loaded.

**Comment by souperneon** [comment]
@thisisaaronland i just tried it by looking https://github.com/domoritz/leaflet-locatecontrol#methods
locator.start();

**Comment by thisisaaronland** [comment]
Ah, interesting. There is nothing in the mapzen.js documentation to indicate that the Locator thing is not our own thing or pointing to the `leaflet-locatecontrol` documentation.

**Comment by souperneon** [comment]
In the README at the bottom it links out to it, but it could be written out in a clearer way in the docs :)

**Comment by thisisaaronland** [comment]
Yes, please. Not least because I am unlikely to get to the bottom of the README once I see that the documentation is somewhere else.

When mz.js is implementing someone else's thing it would be very helpful to call that out explicitly in the documentation for that thing.
