### ISSUE TITLE
Hash control not needed in Mapzen Documentation other than to refer people to use leaflet's

### ISSUE THREAD

**Issue by mpmckenna8** [mapzen/mapzen.js#223]
While making a map I as having trouble getting the location hash in the URL following the documentation on [https://mapzen.com/documentation/mapzen-js/api-reference/#hash-control](https://mapzen.com/documentation/mapzen-js/api-reference/#hash-control)

```
L.Mapzen.hash({
  map: map
})
```

Where in implementation I got it to work just using the old Leaflet one with just L.Hash() which is also in all the examples i think.

**Comment by kkowalsky** [comment]
Can you be more clear? I want to update the documentation to be more clear and haven't seen a problem with the URL hash.

**Comment by hanbyul-here** [comment]
You can use Leaflet Hash with `mapzen.js`, but it is unexpected that `L.Mapzen.hash` is not working. It will help us a lot if you can point the gist or code snippet that you tried to use `L.Mapzen.hash`!

**Comment by mpmckenna8** [comment]
So I was just wrong. I was using tangram.js and loading leaflet.js separately which is why i was not able to use the fancy L.Mapzen functions.  It prob works fine

**Comment by migurski** [comment]
Thanks for reporting your issue all the same @mpmckenna8! This library is new enough that there's bound to be a lot of things we haven't thought of yet.
