### ISSUE TITLE
Customize vector tile key 

### ISSUE THREAD

**Issue by skorasaurus** [mapzen/mapzen.js#225]
Is there a way to specify whose vector key is being used in mapzen.js? I'd just like to be able to roughly see how much usage/viewing I'm getting for my tiles. 

If there's not, are you planning on it or would you rather direct users to go the method of using something like https://github.com/tangrams/cinnabar-style ?

**Comment by hanbyul-here** [comment]
One way I can think is [something like this](https://mapzen.com/tangram/play/?scene=https%3A%2F%2Fapi.github.com%2Fgists%2F2a6334a9c23688384ee43b1200a17dbf#9.9304/37.9149/125.8862) . So you would need to have your own scene file importing mapzen style, but rewriting datasource with your own vector tile key.  Then you can set the path to your own scene file with `scene` option.
```
var map = L.Mapzen.ma('map'.{
scene: 'path-to-scene'
});
```

**Comment by skorasaurus** [comment]
Thank you, that works for me and seems to be a straightforward solution. Closing this; you may want to reopen this if you think this need to be explicitly documented.

**Comment by migurski** [comment]
Yes, thanks for pointing this out, @skorasaurus. We'll talk with the Tangram team to see what a non-hacky approach might be.
