### ISSUE TITLE
Is it possible to turn off scrollwheelzoom, or pass other Leaflet options?

### ISSUE THREAD

**Issue by migurski** [mapzen/mapzen.js#230]
In Leaflet, options are passed in via the constructor. How would we use those options here, if at all?

**Comment by hanbyul-here** [comment]
Users can pass other leaflet options to `L.Mapzen.map`, since `L.Mapzen.map` extends the `L.map` instance including options. 

Users can use syntax like this.

```
      var map = L.Mapzen.map('map',{
        scrollWheelZoom: false,
        scene: L.Mapzen.HouseStyles.Refill
      });
```

**Comment by migurski** [comment]
Thanks, yeah, that we be useful to document. /cc @rmglennon
