### ISSUE TITLE
import non-tiled geojson sources via mapzen.js

### ISSUE THREAD

**Issue by burritojustice** [mapzen/mapzen.js#242]
via mapzen.js, tell Tangram to import a non-tiled GeoJSON source  so lines can appear under labels in house styles, rather than Leaflet dumping spaghetti on top of the map sandwich...

https://mapzen.com/documentation/tangram/Javascript-API/#setdatasource_string_-name-_object_-config

**Comment by hanbyul-here** [comment]
Mapzen.js exposes Tangram Layer and Scene via event. https://mapzen.com/documentation/mapzen-js/api-reference/#draw-a-map 
You can see example of the event showing route line [here](https://github.com/mapzen/lrm-mapzen/blob/gh-pages/js/tangram-route.js#L33)

**Comment by burritojustice** [comment]
cool -- can we get an example of that in the mapzen.js documentation?

**Comment by hanbyul-here** [comment]
Hopefully we can make mapzen.js gallery soon, but meanwhile this example (https://github.com/mapzen/mapzen.js/blob/master/test/examples/isochrone-map.html ) will show how to add geojson sources via mapzen.js
