### ISSUE TITLE
documentation improvement

### ISSUE THREAD

**Issue by hanbyul-here** [mapzen/mapzen.js#248]
- I see `L.Mapzen.map` is part of `Draw a map` at https://mapzen.com/documentation/mapzen-js now. I wonder it could be better to set up the section only for `L.Mapzen.map` api? 
- also it would be nice to have table for `event` section. Currently there is only example code snippe.
- maybe it will be better to detach control from each component name? (Locator control, HAsh control. Geocoder control)

**Comment by kkowalsky** [comment]
I think the "Draw A Map" is just a moniker for L.Mapzen.Map to try to describe it as the action someone is trying to do. Maybe this shows that we should be starting to separate out a quick syntax API reference to make this more discernible. 

I think a table would be good. 

"Control" might not be the perfect name for it, but I think it clarifies the functionality of the different components.
