### ISSUE TITLE
make standalone version official

### ISSUE THREAD

**Issue by hanbyul-here** [mapzen/mapzen.js#251]
- MapzenJS embed Leaflet v0.7, there were already several needs to use other version (1.0), or to use with other plugins based on Leaflet (#212 )
- https://github.com/mapzen/mapzen.js/tree/hanb/standalone This branch has standalone build process, maybe it will be worth to make it official ( and support cdn for it)

**Comment by migurski** [comment]
This is released in v0.3.11 but not yet documented. It’s showing some odd behavior when paired with Leaflet 1.0, so we don't want to shout it from the rooftops until we can learn more about that. Closing this issue.
