### ISSUE TITLE
expose Tangram layer options object

### ISSUE THREAD

**Issue by meetar** [mapzen/mapzen.js#260]
With vanilla Tangram.js, Tangram layer options are set with an options object passed to the `Tangram.leafletLayer` function, like so:

``` javascript
var layer = Tangram.leafletLayer({
    preUpdate: myPreUpdateFunction,
    postUpdate: function(didRender) {
        console.log('postUpdate!');
        if (didRender) {
            console.log('new frame rendered!');
        }
    },
    ...
});
```

The options object is documented here: https://github.com/tangrams/tangram-docs/blob/gh-pages/pages/Tangram-Overview.md#options-object

Some of these options such as `scene` and `attribution` are already settable individually via the mapzen.js `Mapzen.map` function, but not all of them… and once the layer is created, it's too late to set them. Would it be possible to either support them all or expose the leafletLayer.options object directly somehow through mapzen.js?

**Comment by rfriberg** [comment]
Merged.  Will be released with v0.6 (later this week).
