### ISSUE TITLE
Document new Tangram debug option

### ISSUE THREAD

**Issue by migurski** [mapzen/mapzen.js#280]
Follow-on to #279, we’ll need documentation for that option and an appropriate version bump.

**Comment by hanbyul-here** [comment]
I should rename option name from `_debugTangram` to `debugTangram` before documenting it

**Comment by hanbyul-here** [comment]
closed via 5d8e6a5e1d8d417d8a6e52536dab8cb3e35d58a6 , 975078a97a472b56db81e895c33ca7e5cfe7c19d
