### ISSUE TITLE
Expose Tangram's scene object as a non-private element

### ISSUE THREAD

**Issue by thisisaaronland** [mapzen/mapzen.js#284]
Current it's possible to get a hold of Tangram's internal `scene` object via the private Mapzen.js `_tangram/_layer` attributes.

It would be nice to have a public accessor for this. I feel like this is a conversation I've had with @migurski but I don't remember the outcome, if any.

![screen shot 2016-10-28 at 08 52 31](https://cloud.githubusercontent.com/assets/12658759/19812995/9d5f4b78-9cec-11e6-9a0b-ab6e2e00413f.png)

**Comment by migurski** [comment]
Aaron and I talked about this, and I showed him that the `tangramloaded` event passed an event object with a `tangramLayer` property. It’s not documented at [#events](https://mapzen.com/documentation/mapzen-js/api-reference/#events), so let’s add this to the docs. Ideally it would link to the Tangram docs explanation of what a Tangram layer is.

**Comment by hanbyul-here** [comment]
related issue : https://github.com/mapzen/mapzen.js/issues/248
