### ISSUE TITLE
Add pinned version URLs to documentation

### ISSUE THREAD

**Issue by migurski** [mapzen/mapzen.js#297]
Show how a specific major, minor, or patched version can be linked with the URL pattern `https://mapzen.com/js{/version}/{filename}`, e.g.:

* https://mapzen.com/js/mapzen.js (latest)
* https://mapzen.com/js/0/mapzen.js (major)
* https://mapzen.com/js/0.0/mapzen.js (minor)
* https://mapzen.com/js/0.0.0/mapzen.js (patch)

At https://mapzen.com/documentation/mapzen-js/get-started/, we only advertise the latest version URLs. /cc @kkowalsky.

**Comment by kkowalsky** [comment]
would creating a versioning guide like the Cartography docs (https://mapzen.com/documentation/cartography/versioning/) help?

**Comment by migurski** [comment]
I think it’s the right direction!

**Comment by rfriberg** [comment]
Closing, added in #300
