### ISSUE TITLE
Published mapzen.js version is out of date

### ISSUE THREAD

**Issue by nvkelso** [mapzen/mapzen.js#301]
Looks like @rfriberg updated Tangram to `v0.11` [8 days ago](https://github.com/mapzen/mapzen.js/pull/296) in the source code here, but the version of the mapzen.js library published publicly is still at `v0.10`. The public version needs to be updated, please.

Tangram `v0.11` includes required bug fixes to road shield placements. I updated house styles and pushed them to production assuming the Mapzen.js src code and prod were consistent. The shields will look a little weird but not broken broken until this is fixed (I'd prefer not to rollback my change, unless this can't be fixed Wednesday morning).

We should hold @sensescape's road shield blog post until Mapzen.js has been updated on prod as we use Mapzen.js map switcher at the bottom of the post to show off the shields in each styles.

Ideally this would be completed by 12 noon Eastern on Weds. Nov 16th at the latest so we are still within a good blog post window.

**Comment by rfriberg** [comment]
Sorry. We haven't released since that was merged. 

This is fixed.  Mapzen.js v0.5.2 is now out and pulls in Tangram v0.11.

**Comment by nvkelso** [comment]
Verified on prod, thanks for the quick fix!
