### ISSUE TITLE
Update default Leaflet map credit

### ISSUE THREAD

**Issue by nvkelso** [mapzen/mapzen.js#303]
We currently say:

* [Mapzen](https://mapzen.com/) - [Attribution](https://www.mapzen.com/rights), Data ©[OSM](https://openstreetmap.org/copyright) contributors, [Leaflet](http://leafletjs.com/)

I propose something shorter and also more expansive:

* [Mapzen](https://www.mapzen.com/rights), Data © [OpenStreetMap](https://openstreetmap.org/copyright) contributors, [Leaflet](http://leafletjs.com/)

**Comment by rfriberg** [comment]
Happy to do this. Any objections @migurski @hanbyul-here ?

**Comment by nvkelso** [comment]
To clarify – I propose the attribution link be around `Mapzen`.

**Comment by migurski** [comment]
No particular objections, but whatever we do should be consistent with https://mapzen.com/rights/.

**Comment by rfriberg** [comment]
According to that page, we should be using: 

Powered by <a href="https://mapzen.com">Mapzen</a> - <a href="https://www.mapzen.com/rights">Attribution.</a>. Data ©<a href="https://openstreetmap.org/copyright">OSM</a> contributors. 

Even double period aside, it's a bit lengthy once you add in the Leaflet attribution. Who make the last call on this?

**Comment by rmglennon** [comment]
We recently updated the rights document to simplify the text. https://mapzen.com/rights/

**Comment by rfriberg** [comment]
👍  Thanks @rmglennon!
