### ISSUE TITLE
Put Routing components

### ISSUE THREAD

**Issue by hanbyul-here** [mapzen/mapzen.js#316]
I am already working on it, but this drags out some bigger issues, so I wanted to write them down. 

- [x] Save api key somewhere so all components can share it : Currently, search component is the only component which requires api  key, so users is passing the key when initializing search component. I think it will make sense to pass the api key with initialization of the map? (not required if you just want to render a map, but required if you want more components?) 
- [x] consolidate ajax methods among components: Search component is using hand-rolled one, and routing component is using `corslite`. 
- [x] modularize `lrm-mapzen` so mapzenjs doesn't have to use global name to accept the instance.

**Comment by hanbyul-here** [comment]
- Brand LRM style 
 - [ ] route line, marker
 - [ ] match the padding between components 
 - [ ] review icons used for costing options and directions
 - [ ] make it mobile friendly (considering other components)

**Comment by rfriberg** [comment]
**Suggestions for UI updates:**  (most of which will apply to lrm-mapzen but leaving here for now)

- Custom colors for route lines (as noted above: #06a6d4 by default, dashed line for walking, solid for others)
- Custom colors/icons for waypoints - ?
- Fix borders around "x" buttons on start/end text inputs
- Add left padding to start and end text inputs
- Increase font-size (~14px) to improve overall readability
- Increase white space between navigation steps
- Add left padding to start and end text inputs
- "Reverse waypoints" and "Add waypoint" buttons should be same height and width and same icon line thickness
- Add title attribute to "Reverse waypoints" and "Add waypoint" buttons to provide some context about what these buttons do
- Add error messages to UI (by default)
- Default to imperial units - ?
- Allow show/hide or minimization of navigation directions (or entire UI?)
- Resize UI on window resize
- Fix positioning on small screens to the UI doesn't overlap with Scarab (see screenshot below)

**Other suggestions:**
- Add buttons to toggle costing modes (this is probably a v2 item)



**Current view:**

<img width="552" alt="screen shot 2017-05-25 at 9 20 16 am" src="https://cloud.githubusercontent.com/assets/1463386/26459550/b45d1cb8-412b-11e7-8b41-38d1f5d0268e.png">

**Comment by hanbyul-here** [comment]
@rfriberg thanks for the comment! I handled some of suggestions (I put priority on the things that I can do by myself. Image assets, and some UI polishment.. I probably would need @souperneon 's help) 
Also there are restrictions from Leaflet Routing Machine too. Ex. [+] button is being attached inside of Leaflet Routing Machine, we don't have much control on it. Error control falls same case. (I remember I mention this as fixable problem. It turned out we can't really put errorControl as default for now. Users would need to [put additional syntax](https://github.com/mapzen/mapzen.js/pull/387/files#diff-e10d07ec169570f8ccf474302740c619R70) to handle error with UI. Sorry!  ) 
We can probably move this ticket to `lrm-mapzen` repo, keep improving styles.

**Comment by rfriberg** [comment]
Thanks @hanbyul-here!

Adding the errorControl - is that something we could do in mapzen.js but not in lrm-mapzen?  I think setting up a customized routing component with opinionated defaults in mapzen.js is just fine.

Yes, feel free to open a ticket on `lrm-mapzen` to capture any of this work that can be done there.  The rest we can discuss and hopefully update in mapzen.js.

**Comment by hanbyul-here** [comment]
@rfriberg I can't think of any way to set up default error UI (Neither in lrm-mapzen nor mapzen.js) for now without touching `control.js` of LRM. LRM doesn't know about error control, it is the error control which is aware of LRM. LRM instance is passed to errorControl, making the error UI reacting to its events. (Syntax is `L.Mapzen.routing.errorControl(routingControl).addTo(map);`) 

Yes, we should document this and I will make sure this goes to every example.
