### ISSUE TITLE
Search box collapses when expanded = true

### ISSUE THREAD

**Issue by rfriberg** [mapzen/mapzen.js#326]
One of the geocoder options allows the user to keep the search box in the expanded state by setting `expanded: true`.  [See docs](https://mapzen.com/documentation/mapzen-js/search/#set-the-search-appearance-and-interaction-behavior)

This currently works as expected on initial page load but not on window resizing.

**Comment by rfriberg** [comment]
Looking into this a little, I'm realizing that I don't quite understand the intent of `expanded` and `collapsible`.  @hanbyul-here do you have a good idea of what each of these is supposed to do?

**Comment by hanbyul-here** [comment]
Thanks for pointing out this issue. I was not aware of this. 
`expanded` is for a search box to be expanded when it is first loaded, and `collapsible` is for a search box to be responsible for screen size. I tweaked its default value to give mapzen.js desirable behavior for demos. ( inspired from [Mapzen Scasrab search box](https://github.com/mapzen/scarab/blob/master/src/components/search/search.js) )  

I addded a check for `collapsible` option before it executes `_checkResize`, and it seems to fix the problem? (https://github.com/mapzen/mapzen.js/blob/hanb/searchbox-fix/src/js/components/search.js#L638)

**Comment by rfriberg** [comment]
Cool.  Yeah, that check should work just fine. Thanks!  I'll update the docs to reflect this differentiation.  :)  (Feel free to take this ticket and close it with your PR.)
