### ISSUE TITLE
New bug in 0.6: absolute URLs for scene files fail

### ISSUE THREAD

**Issue by migurski** [mapzen/mapzen.js#340]
In Mapzen.js 0.5.5, this code snippet works when used from http://127.0.0.1:5000/:

```javascript
var map = L.Mapzen.map('map', {
  scene: "/scene.yaml",
  center: [37.318373, -122.028352], zoom: 16
});
```

In Mapzen.js 0.6.0, it fails with this error (note the double slash in the error URL):

```
[Error] Tangram v0.11.6 [error]: Failed to import scene: http://127.0.0.1:5000//scene.yaml
	error
	s (tangram.min.js:17:23865)
	(anonymous function) (tangram.min.js:13:2415)
	forEach
	(anonymous function) (tangram.min.js:13:2354)
	s (tangram.min.js:2:8839)
	(anonymous function) (tangram.min.js:2:8961)
	l (tangram.min.js:1:31541)
```

I can make it work by using a relative URL for the scene file:

```javascript
var map = L.Mapzen.map('map', {
  scene: "scene.yaml",
  center: [37.318373, -122.028352], zoom: 16
});
```

This is a similar error to https://github.com/tangrams/tangram/issues/477, but I believe it’s in Mapzen.js.

**Comment by hanbyul-here** [comment]
After spending some time on this issue, I could narrow down this path problem is coming from the syntax below.
```
var layer = Tangram.leafletLayer({ 
  scene: {
    import: '/scene.yaml',
    global: { sdk_mapzen_api_key: ''}
  }
});
```
We are not using exact same syntax, but we do [build scene object](https://github.com/mapzen/mapzen.js/blob/master/src/js/components/tangram.js#L81-L88) having api key in it. My guess is Tangram handles path differently when it was passed as an object and making problem with absolute path. Can you confirm this @bcamper @meetar ?

**Comment by bcamper** [comment]
The fix in https://github.com/tangrams/tangram/issues/477 is queued for Tangram JS v0.11.7, which I hope to release today - but it is not live yet. (I should have clarified on that issue, I usually post the commit that resolves the issue, but leave the issue itself open until it is publicly released. In this case, @migurski closed the issue and I forgot to re-open it :)

**Comment by migurski** [comment]
So this is the same underlying issue as the Tangram one?

**Comment by bcamper** [comment]
Unless mapzen.js is doing some explicit URL manipulation, I believe it is based on the error message (which looks like it's coming from tangram). I will try to have this resolved today.

**Comment by hanbyul-here** [comment]
confirming mapzen.js is not doing any URL manipulation for the scene file!

**Comment by migurski** [comment]
Okay, great! I had thought it might be a Mapzen.js problem due to how it worked fine in 0.5.5, but maybe that calls a different underlying version of Tangram.
