### ISSUE TITLE
documentation fix for apikey to map object (or make mapzen.js behave as documented)

### ISSUE THREAD

**Issue by hanbyul-here** [mapzen/mapzen.js#343]
Currently mapzen.js map object doesn't accept `apiKey` as one of options. Documentation is behind. gotta fix this https://github.com/mapzen/mapzen.js/blob/72c318aec9b07838ba967cd17c4c20ef96983e38/docs/api-reference.md#options

orrr

merge @rfriberg 
's change (accept `apiKey`as an option and set it as a global key) to master so mapzen.js behaves as documented https://github.com/mapzen/mapzen.js/commit/8cf06511ed9dbc65ddb8c979fa5bb17b704f6b1c

**Comment by nvkelso** [comment]
For context: I ran into this today doing the 2016Q4 basemap style update.

FWIW: I prefer merging @rfriberg's change.

**Comment by rfriberg** [comment]
I'd prefer to merge my change.  I'll update and make a PR today.

**Comment by hanbyul-here** [comment]
Leaving a note for future:
If we start allowing users to create more than two maps ( == Once Tangram starts allowing creating more than two maps on a browser context), this decision can be bit confusing for users. 
1. The key passed to the map object takes over global key. This means that even if users pass two different keys to two maps object, the key for the map created later will be used for both of maps.
2. It is likely that users would expect the key to be used for the components attached to the map. (Especially if different keys were set for each map) But currently we don't pass the api key of the map to the components added to it. 

I'd like to revisit these concerns when we are ready for 2️⃣ maps

**Comment by hanbyul-here** [comment]
closed with 2673acfa2ab733b7ce6705dbf1c49fa429c1f262
