### ISSUE TITLE
add info button to scarab for popup panel

### ISSUE THREAD

**Issue by burritojustice** [mapzen/mapzen.js#383]
add a pop-up info button to the scarab. 

![image](https://cloud.githubusercontent.com/assets/3979711/25756596/29b98682-317c-11e7-9d63-d781554f81cc.png)

![image](https://cloud.githubusercontent.com/assets/3979711/25758141/318a9314-3182-11e7-94bb-61b8270b0870.png)

```
L.Mapzen.bug({
  name: 'Web Map',
  link: 'https://erasermap.com/maps',
  tweet: '@mapzen',
  repo: 'https://github.com/mapzen/web-map'
  info: 'a few dozen words of explanatory text (and html for links)'
});
```
This would pop up and go away on a click.

**Comment by burritojustice** [comment]
It could even hold an image for a legend...

**Comment by hanbyul-here** [comment]
I think this issue would make more sense to go to Mapzen Scarab repo? https://github.com/mapzen/scarab

**Comment by burritojustice** [comment]
that's fine by me

**Comment by hanbyul-here** [comment]
Thanks for moving the issue! @burritojustice (https://github.com/mapzen/scarab/issues/1)
