### ISSUE TITLE
Specifying API key with Geocoder component in 0.6.12 fails

### ISSUE THREAD

**Issue by nvkelso** [mapzen/mapzen.js#389]
Looks like `v0.6.12` has both new v5 Walkabout changes as intended, and also Geocoder changes which weren't documented in the changelog and cause problems for me in the wild for the bike map product page.

https://github.com/mapzen/mapzen.js/compare/release-v0.6.11...master

If I ask for it like I've historically done:

```
L.Mapzen.geocoder('search-Y2Sr2RD').addTo(map);
```

Then I get the following error:

<img width="1440" alt="screen shot 2017-05-11 at 12 10 48" src="https://cloud.githubusercontent.com/assets/853051/25967434/f5b32a2a-3642-11e7-8104-a8df0f412cc7.png">

But if I ask for without the API key then it'll follow the other code path using the generic API key defined for Mapzen.js instead of a custom Geocoder api key:

```
L.Mapzen.geocoder().addTo(map);
```

Since I don't _need_ the custom Geocoder API key I've removed that from my code and can still use latest. I also tried pegging to `v0.6.11` using the custom Geocoder API key and that worked, but seemed brittle.

**Comment by hanbyul-here** [comment]
Thanks for the report @nvkelso . This bug happened while trying to keep user's attribution but also overwriting the attribution leaflet-geocoder offers by default. Current fix for this was just released (v0.6.14).
