### ISSUE TITLE
Initializing multiple maps triggers error if WebGL is not available

### ISSUE THREAD

**Issue by everhardt** [mapzen/mapzen.js#401]
When initializing a map for the first time with `L.Mapzen.map` in an environment that does not support WebGL it works, giving the following console.log:

> WebGL is not available, falling back to fallbackTile option.

But, when running a second map initialization through `L.Mapzen.map`, whether on the same DOM-element or another, it causes the following uncaught error:
> tangram.min.js:12 Uncaught Error: Couldn't create WebGL context. Your browser may not support WebGL, or it's turned off? Visit http://webglreport.com/ for more info

It seems to be caused by the fact that Tangram is already initialized the second time and that then automatically WebGL is chosen, also if the browser does not support that, see https://github.com/mapzen/mapzen.js/blob/b49d9bde9c34f03be8d9391e5a49ab635d64ac16/src/js/components/tangram.js#L41

By adding `Tangram = undefined;` just before initializing the map is a quick fix.

**Comment by hanbyul-here** [comment]
Thanks for reporting! Indeed mapzen.js was not handling the cases with more than one map without WebGL well. The fix for this issue will be ready to release soon!
