### ISSUE TITLE
Pelias layers/sources filters not being passed along during autocomplete requests?

### ISSUE THREAD

**Issue by thisisaaronland** [mapzen/mapzen.js#406]
Not sure if this is a `mapzen.js` thing or `leaflet-geocoder` thing (cc @louh) or both?

It appears that Pelias arguments for filtering layers/sources passed to the mapzen.js search widget constructor are not being included with queries to the Pelias autocomplete endpoint. 

For example, this:

https://github.com/whosonfirst/electron-whosonfirst-bookmarks/blob/master/javascript/mapzen.whosonfirst.bookmarks.trips.js#L387-L409

Results in this:

https://search.mapzen.com/v1/autocomplete?text=Hawaii&focus.point.lat=-0.26315696950531126&focus.point.lon=0.2631578947368096&api_key=mapzen-xxxxxx

Or maybe I am just doing it wrong?

**Comment by hanbyul-here** [comment]
mapzen.js doesn't really do anything other than importing and putting it under the L.Mapzen namespace. This should be a `leaflet-geocoder` issue. Will you move this issue to [geocoder repo](https://github.com/mapzen/leaflet-geocoder)?

**Comment by louh** [comment]
This has to do with `mapzen.js` syntax so I think leaving it here is fine. 

Instead of doing this:

```js
var geocoder = L.Mapzen.geocoder();
geocoder.addTo(map, opts);
```

Try this:

```js
var geocoder = L.Mapzen.geocoder(undefined, opts);
geocoder.addTo(map);
```

**Comment by thisisaaronland** [comment]
Oh I see, yes. I was passing the options to the wrong thing-y. I've updated things in my code but still the extra Pelias params don't appear to be append to the request across the wire:

https://github.com/whosonfirst/electron-whosonfirst-bookmarks/blob/master/javascript/mapzen.whosonfirst.bookmarks.trips.js#L390-L407

**Comment by louh** [comment]
Ah - I wrote it wrong. By setting the first argument (where it might expect a string for an api key) to a falsy value we end up overwriting the options. I haven't fully traced where this takes place, but this should work better:

```js
var geocoder = L.Mapzen.geocoder(opts);
geocoder.addTo(map);
```

The geocoder plugin is actually set up to allow api keys to be optional. In our case by omitting the API key, mapzen.js should use the one that's set up for the entire library. We were causing problems by making it undefined in that first argument.

**Comment by thisisaaronland** [comment]
That works! Thanks.
