### ISSUE TITLE
Initializing multiple maps doesn't work if scene is an object

### ISSUE THREAD

**Issue by bfirsh** [mapzen/mapzen.js#411]
Works: https://jsfiddle.net/bfirsh/pewezf5u/
Doesn't work: https://jsfiddle.net/bfirsh/8mk41cw0/

The only difference is that in the former `scene` is a string to a ZIP file, and in the latter it's an object with some extra options.

After doing some digging through issues, it seems like Tangram can only be initialised once, but it looks like there is some smarts to reuse a Tangram singleton. That seems to be working when the scene is just a string, but not if it's an object with extra options.

**Comment by hanbyul-here** [comment]
🤔  As far as I know, Tangram doesn't allow the initialization of the map more than one on one browser context. It is very interesting that it changes behaviors when the scene is a string. Before I look into mapzen.js layer of Tangram, I would love to hear more on this issue from Tangram team. Any idea? @meetar @bcamper ?

**Comment by bfirsh** [comment]
For anyone else running into this issue, I solved it by managing my own Tangram singleton. I initialize like this:

```javascript
    if (tangramLayer === null) {
      tangramLayer = window.Tangram.leafletLayer({
        scene: {
          import: Mapzen.BasemapStyles.Walkabout,
          global: {
            sdk_path_overlay: false,
            sdk_bike_overlay: true,
            sdk_mapzen_api_key: Mapzen.apiKey
          }
        }
      });
    }
```

Then when initializing the map, I use `L.map()` instead of `Mapzen.map()`, and attach tangram with `tangramLayer.addTo(map)`.

When unloading the map, I call `tangramLayer.remove()`. It then successfully reattaches to a new map.

**Comment by hanbyul-here** [comment]
@bfirsh Yes! that is also how Tangram team recommends to [reuse Tangram Layer] (https://github.com/tangrams/tangram-docs/commit/f6fcf6e809778808842e78bccb4b04ec23854f40) You can access to tangramLayer instance [through the event]((https://mapzen.com/documentation/mapzen-js/api-reference/#events) ) using mapzen.js.

We consider Mapzen.js a convenient hub for Mapzen products, delivering what its embedded components do (hopefully) straightforwardly. Mapzen.js wouldn't do much about this multiple map initialization issue on its level. However, Tangram team is working on multiple maps. (You can read more about it [here](https://github.com/tangrams/tangram/issues/350) ). 

I am not sure what Tangram 0.13 (with a release of (0.8.1)[https://github.com/mapzen/mapzen.js/releases/tag/release-v0.8.1]) did for your example, but it seems your both fiddles work. (Also, Tangram became [bundlable](https://www.npmjs.com/package/tangram), so mapzen.js is going to move away from dynamically injecting Tangram script to the page, exposing Tangram under window namespace. There is going to be  at least a minor version number version change when this happens.)
