### ISSUE TITLE
Upgrade to Tangram 0.13

### ISSUE THREAD

**Issue by nvkelso** [mapzen/mapzen.js#413]
Tangram [v0.13](https://github.com/tangrams/tangram/releases/tag/v0.13.0) was released "26 days ago" but released Mapzen.js still uses Tangram v0.12. 

Primarily v0.13 adds curved label support for Arabic, bug fixes, and new feature that Mapzen.js wouldn't necessarily make use of right away. But it's important to keep our latest face forward.

https://github.com/mapzen/mapzen.js/blob/master/src/js/components/tangram.js#L9

/cc @bcamper

**Comment by bcamper** [comment]
I already have an open PR for this #412, but tests are broken because our BrowserStack plan needs to be renewed, and we are working with them to get open source sponsorship. @hanbyul-here is helping with that.

**Comment by hanbyul-here** [comment]
closed via 5abc5aac6235726c40be06973dee087e26915214
