### ISSUE TITLE
Links to Leaflet API reference docs redirect to the top of the page

### ISSUE THREAD

**Issue by rmglennon** [mapzen/mapzen.js#422]
All the links to anchors in the Leaflet API docs in https://mapzen.com/documentation/mapzen-js/search/ now redirect to the top of the API reference.

For example, http://leafletjs.com/reference.html#latlngbounds redirects and goes to the top of the page.

Current link is: http://leafletjs.com/reference-1.2.0.html#latlngbounds

It looks like there is no longer a "latest" or "current" release documentation with a stable URL, so I do not think it will be worth us updating every link each time a new version is released. This may mean removing these anchors altogether.

**Comment by rmglennon** [comment]
See https://github.com/Leaflet/Leaflet/issues/5508

**Comment by rfriberg** [comment]
Thanks @rmglennon - it looks like Leaflet just fixed this   :)
