### ISSUE TITLE
Documentation for results properties

### ISSUE THREAD

**Issue by stevage** [mapzen/mapzen.js#429]
I'm having trouble finding any documentation on the actual content of the geocoded responses – the meaning of "neighbourhood", "localadmin", "name" and so on. There are several places that kind of address this:

- [Autocomplete#layers](https://mapzen.com/documentation/search/autocomplete/#layers) lists the available layers, which kind of correspond to the properties (but not every property is a layer)
- [Structured geocoding parameters](https://mapzen.com/documentation/search/structured-geocoding/), which lists the things you can search on - but you can't search on everything.
- [Who's on first mapping reference](https://mapzen.com/documentation/search/structured-geocoding/#whos-on-first-layer-mappings-reference) - again, not complete.

In particular, I'm trying to find a definition for the `"name"` property, and trying to find a way to unambiguously map Search results into our app's address fields, such as "Address line 1".

This SDK may not be the right place to definitively define these fields, but a couple of links to the right documentation (if there is any) would be very helpful.

**Comment by rmglennon** [comment]
Hello, @stevage - thanks for your note.

The "name" is basically a label. It could be a business name, a city, or an address, depending on what is being searched for and what is returned. 

You can use the "housenumber" and "street" properties to get the equivalent of address line 1. However, for address searches, these are brought together under the "label" property as a convenience to save you from having to reassemble the address yourself (which can be tricky if your customers could have addresses where numbers could be either before or after the street name).

Regarding neighbourhood, localadmin, and so on -- these are Who's on First placetypes. Better formatted documentation is coming, but here are some raw files if you need more information: https://github.com/whosonfirst/whosonfirst-placetypes.

If more documentation is needed, it can go in the Mapzen Search API documentation.

**Comment by rmglennon** [comment]
More docs on name property:

https://mapzen.com/documentation/search/response/#name

Please reopen or send a note to hello at mapzen dot com if you need more help!
