### ISSUE TITLE
Security of api-key

### ISSUE THREAD

**Issue by robincafolla** [mapzen/mapzen.js#445]
I've just started using your api, so I may be missing something obvious, but what prevent's another user lifting my api-key from my page, using it on their site and using up my resource allowance? I don't see any origin settings on the dashboard limiting where the key can be used from and your docs all have the key in plain JS.

**Comment by kkowalsky** [comment]
Hi @robincafolla! We recommend setting up a [proxy](https://mapzen.com/documentation/overview/api-keys/#protect-your-api-keys) to protect your API key. Feel free to send us any further questions to hello@mapzen.com
