### ISSUE TITLE
Uncaught TypeError: Cannot read property 'src' of null

### ISSUE THREAD

**Issue by marianoguerra** [mapzen/mapzen.js#451]
hi, I started having the error in the title with the latest version,

I found the culprit, which doesn't seem to be your fault but the result of the build.

this line in the build:

     document.currentScript !== undefined

the problem is that in my code for some reason document.currentScript is null.

the fix is to change the line to:

    !!document.currentScript

or just plain:

    document.currentScript

and the code loads.

extra info in the tangram issue: https://github.com/tangrams/tangram/issues/625

I know this is not your problem but it affects your build.

**Comment by marianoguerra** [comment]
follow the PR here: https://github.com/tangrams/tangram/pull/626

**Comment by hanbyul-here** [comment]
Thanks for the note!
