### ISSUE TITLE
access to Mapzen Terrarium Terrain/Elevation Dataset via Mapzen.js?

### ISSUE THREAD

**Issue by geospatialmapmashup** [mapzen/mapzen.js#452]
Decoding Terrarium PNG format in browser without server. in Leafletjs? Do you have any code that works in browser for accessing and decoding your mapzen terrarium PNG format?

**Comment by hanbyul-here** [comment]
Hi! You can see the example cod decoding elevation tile with Tangram [here](https://github.com/tangrams/terrain-demos/blob/master/styles/terrarium-elevation.yaml#L24-L51)
